$(function(){
    if(location.search.indexOf("kwords=")!=-1){
      var kwords=decodeURI(
        location.search.split("=")[1]
      );
            new Vue({
              el:"#main",
              data:{
                products:[],
                count:"",
                pageCount:"",
                pno:0,
                i:"",
                res:[],
                dis:{dis1:false,dis2:false},
                prevOne:"",
                nextOne:"",
                more:{more1:"更多",more2:"更多"},
                img:{src1:"img/product/new-arrow-down_d9805e9.png",src2:"img/product/new-arrow-down_d9805e9.png"}
              },
              methods:{
                show(i){
                  if(i==1){
                    if(this.dis.dis1==false){
                      this.dis.dis1=true;
                      this.more.more1="收起",
                      this.img.src1="img/product/new-arrow-up_d9805e9.png"
                      }
                      else{
                        this.dis.dis1=false;
                        this.more.more1="更多",
                        this.img.src1="img/product/new-arrow-down_d9805e9.png"
                      }
                  }else if(i==2){
                    if(this.dis.dis2==false){
                      this.dis.dis2=true;
                      this.more.more2="收起",
                      this.img.src2="img/product/new-arrow-up_d9805e9.png"
                      }
                      else{
                        this.dis.dis2=false;
                        this.more.more2="更多",
                        this.img.src2="img/product/new-arrow-down_d9805e9.png"
                      } 
                  }
                 
                  
                },
                prev(){
                  if(this.prevOne!="disabled"){
                    this.pno--;              
                    this.getList()
                  }
                },
                next(){  
                if(this.nextOne!="disabled"){
                  this.pno++;
                  this.getList()
                }
                },
                jump(i){
                  this.pno=i-1
                  this.getList()
                },
                getList(){
                  axios.get("http://localhost:3000/products",{
                    params:{kwords:kwords,pno:this.pno}
                  }).then(res=>{
                    console.log(res) 
                                   
                 this.products=res.data.products
                 this.count=res.data.count
                 this.pageCount=res.data.pageCount  
                 if(this.pno==0){
                  this.prevOne="disabled";
                }else{
                  this.prevOne="";
                } 
                if(this.pno==this.pageCount-1){
                  console.log(this.pageCount)
                  this.nextOne="disabled";
                }else{
                  this.nextOne=""; 
                }          
                  })  
                  
              },
              },
              mounted(){
                this.getList();
              },
              })
    }
  })